### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by seriema** [bower/search#28]
I'm getting this AJAX error on just visiting http://bower.io/search/
````
XMLHttpRequest cannot load https://bower-component-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://bower.io' is therefore not allowed access.
````

**Comment by slavaschmidt** [comment]
+1

**Comment by Jnull** [comment]
![bower - search package error](https://cloud.githubusercontent.com/assets/3529087/6890711/5e99aaa4-d665-11e4-8ff2-8a8ed456d9c6.png)

**Comment by samccone** [comment]
yep we are well aware of this :+1: :+1: :+1:

**Comment by mgntrn** [comment]
Search is still broken?

**Comment by Jnull** [comment]
Its working now for me.  This should be closed.

**Comment by samccone** [comment]
It does seem to be working now, however it was down again when I reopened it. I think this may have been caused by a new deployment, but I am not sure who deployed the site

**Comment by desandro** [comment]
This issue was for an older search issue. See #69 for most recent issue.

**Comment by samccone** [comment]
:+1:
