### ISSUE TITLE
tap not showing up

### ISSUE THREAD

**Issue by desandro** [bower/search#57]
[`tap` is registered](http://bower.herokuapp.com/packages/tap), but not showing up on http://bower.io/search/?q=tap%20owner:pukhalski

``` json
{
  "name": "tap",
  "url": "git://github.com/pukhalski/tap.js.git"
}
```

@pukhalski

**Comment by pukhalski** [comment]
@davidjbradshaw, @fahad19, updated bower.json. Any need to bump the version to update it in the registry?

**Comment by desandro** [comment]
Yes, you will need to tag a new release to see changes in bower.json

**Comment by pukhalski** [comment]
@desandro, still not there. Any cure so far?

Thanks.

**Comment by davidjbradshaw** [comment]
@pukhalski see [/bower/search/issues/36#issuecomment-73905078](https://github.com/bower/search/issues/36#issuecomment-73905078).

**Comment by pukhalski** [comment]
@davidjbradshaw, thanks. Apparently found another issue: "Must be a collaborator on GitHub.com". I am the owner of the repo actually...

**Comment by davidjbradshaw** [comment]
@pukhalski https://github.com/jlong/sass-bootstrap-defunct/issues/143#issuecomment-42128071

**Comment by davidjbradshaw** [comment]
Fixed https://github.com/bower/search-server/pull/21.
