### ISSUE TITLE
Getting intermittent database errors

### ISSUE THREAD

**Issue by panozzaj** [bower/search#59]
I am not sure if this is the right place to file issues for https://bower.herokuapp.com, but I thought this was important. If you know of a better place to direct this, please let me know.

When I hit (for example) https://bower.herokuapp.com/packages/angular-bootstrap, about half of the time I see "Database Error" with status code 500. The other half of the time I am seeing the normal resource description:

```
{"name":"angular-bootstrap","url":"git://github.com/angular-ui/bootstrap-bower.git","hits":2209805}
```

I am wondering what the database error is and how I can get around this. Currently this is causing our continuous integration build to fail. Thanks for your help!

**Comment by desandro** [comment]
We've been experiencing downtime with our registry for the past week. We're hustling with Heroku to get it back up and running with better capacity. I apologize for the outage. I appreciate your patience as we work through this.

**Comment by sheerun** [comment]
I switched back to 1 dyno, but with 2x more computing power. It probably should be fine now.

We need to do research why 2 dynos fail (probably limited database connections).

**Comment by panozzaj** [comment]
@desandro @sheerun thanks for your quick responses and your work on the project. Running something like this can be a thankless job, no one notices until it falls down. :) at least that was my experience when maintaining servers.

Manual testing seems to show that the example URL is working now. We can either leave this open until the underlying issue is fixed or we can open a new issue for the infrastructure investigation (your call). Thanks again!

**Comment by sheerun** [comment]
I needed to enable 2 dynos again, because app repeatedly crashed on one 2x dyno. See #1385

I also restarted application, and I'm waiting for Mat to upgrade postgresql / transfer ownership.

**Comment by dav-** [comment]
I'm getting some CORS errors while trying to search for packages on /search/. Not sure if this is related to this issue, but it seems like it may be.

    Failed to load resource: the server responded with a status of 418 (I'm a teapot)

    bower.io/:1 XMLHttpRequest cannot load https://bower-component-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://bower.io' is therefore not allowed access. The response had HTTP status code 418.`

Maybe the server is down right now, which is why the access control header isn't being sent?

**Comment by vegetableman** [comment]
facing this issue as well

**Comment by sheerun** [comment]
It seems it happens every time we deploy registry... Probably connected with filling cache.

Someone needs to implement caching entries in Mongo instead of memory.

**Comment by davidjbradshaw** [comment]
The issue is that the data is all held in memory and the script terminates every 24 hours. When it restarts it takes a few minutes to download the first 5,000 records from GitHub during which time it's a teapot without data, it then continues to download data for the next few hours, pausing each time it hits the API limit.

I want to used MongoDB to sort this out but have not had the time. Another option that might be simpler and more reliable is to have the script run on another server and upload the data to GitHub every few hours.

**Comment by sheerun** [comment]
It seems fine now as main registry stabilized
