### ISSUE TITLE
Search is not case sensitive

### ISSUE THREAD

**Issue by pirj** [bower/search#62]
E.g. 'ink' vs 'Ink'. Both are quite popular. However, 'Ink' appeared earlier, while 'ink' is more popular. Search only finds the later. CLI bower finds both:

```
$ bower info ink
bower ink#*                     cached git://github.com/zurb/ink.git#1.0.
$ bower info Ink 
bower Ink#*                     cached git://github.com/sapo/Ink.git#3.1.4
```

**Comment by davidjbradshaw** [comment]
The second one appears as InkJS in the web search.

http://bower.io/search/?q=InkJS

**Comment by pirj** [comment]
@davidjbradshaw What if they didn't have this InkJS at all, would any query reached Ink at all?

[Author claims](https://github.com/sapo/Ink/issues/427#issuecomment-75429544) that name is Ink.

**Comment by adityadineshsaxena** [comment]
I see both Zurb's and the OP's Ink repos present in the current search. I was able to observe this on a local instance of the search client as well. Please refer to the screenshot below.

![screenshot 2015-05-18 11 34 00](https://cloud.githubusercontent.com/assets/993800/7675119/d3b89120-fd51-11e4-8d4b-726f977b7d14.png)
@davidjbradshaw / @pirj  : Could this issue be closed now?

**Comment by pirj** [comment]
@adityadineshsaxena absolutely. Thanks
