### ISSUE TITLE
Searching for "jQuery" does not show the jQuery package

### ISSUE THREAD

**Issue by accidentaldeveloper** [bower/search#66]
On the search page, a search for "jQuery" shows a variety of related packages, but the jQuery package itself does not appear anywhere on the first page. I'm totally new to Bower, so I may not understand the logic behind the search. However, I would think that searching by package name would  be a common use case.
![image](https://cloud.githubusercontent.com/assets/5819232/6757443/6aff1abe-cf07-11e4-9226-dceb142e34ba.png)

**Comment by davidjbradshaw** [comment]
jQuery is missing a `bower.json' file.

**Comment by patrickkettner** [comment]
[yes they do](https://github.com/jquery/jquery/blob/2.1-stable/bower.json)

[see here](https://github.com/jquery/jquery/issues/1673)

**Comment by davidjbradshaw** [comment]
The websearch takes this from the git repo and they are not checking it in.

**Comment by patrickkettner** [comment]
they _are_ checking it in. I linked to it. Do you mean it has to be in master?

**Comment by davidjbradshaw** [comment]
yep.

On Fri, Mar 20, 2015 at 7:26 PM, patrick kettner <notifications@github.com>
wrote:

> they *are* checking it in. I linked to it. Do you mean it has to be in
> master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bower/search/issues/66#issuecomment-84108192>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by accommodavid** [comment]
No updates to this in almost a year, looks like jQuery is not going to check the file in on the master branch. Should I close?

**Comment by BenMann** [comment]
Indeed they have a special [`jquery-dist`](https://github.com/jquery/jquery-dist) repo for that. I think it's safe to close though and account for that in the re-write of the registry / search by just showing all packages registered.
