### ISSUE TITLE
bower.io search broken - Access-Control-Allow-Origin error

### ISSUE THREAD

**Issue by orls** [bower/search#67]
```
XMLHttpRequest cannot load https://bower-component-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://bower.io' is therefore not allowed access. The response had HTTP status code 418.
```

Search box is only searching within the handful of front-page packages, and the next buttons aren't working; giving the impression bower only has 16 packages available, all from 9 months ago ;)

**Comment by albertinad** [comment]
I'm getting the same status code: 418 since the whole day. It seems that the server can't get the list of packages or an issue related to github DDoS these days?

![bower-search-error](https://cloud.githubusercontent.com/assets/2309921/6888493/e1a4602a-d655-11e4-8cb3-7ea9e889236c.png)

**Comment by samccone** [comment]
yep 418 "empty tea pot" is caused by the search server being unable to update the registry cache, thus being filled with empty results. Alas this is a result of the non robust form of in memory cache that the search server is using paired with github being in a nasty state due to the DDOS.

**Comment by samccone** [comment]
Related
https://github.com/bower/search/issues/59
