### ISSUE TITLE
Unable to find my component in search results

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [bower/search#68]
I have created a bower component `ionic-timepicker` long ago. I am able to install the package by `bower install ionic-timepicker`, but when i search for this at http://bower.io/search/, i cannot see the results for my search. Could you please let me know the reason, why i cannot see it in the search results.

**Comment by desandro** [comment]
Looks to be showing up fine http://bower.io/search/?q=ionic-timepicker

**Comment by rajeshwar-fissionhq** [comment]
I am not sure why this is happening. I raised the same bug before and when they said it was working, it was really working fine. Today i searched again and i didn't find it. After raising this issue i am able to see now. Any ways thanks. As of now i can see it.
