### ISSUE TITLE
Online search page lost projects

### ISSUE THREAD

**Issue by alvarotrigo** [bower/search#71]
I was checking http://bower.io/search/ the other day and I noticed many projects have disappeared from the search results, such as:

- impress.js
- reveal.js
- three.js
- skrollr

Is there any reason under it?

**Comment by samccone** [comment]
It looks like the data is still there 

![screen shot 2015-04-21 at 9 16 19 am](https://cloud.githubusercontent.com/assets/883126/7252952/20085e80-e807-11e4-90a5-68c38f50f31d.png)

Whenever we deploy the in memory cache of projects gets cleared and it has to regrab the projects from github (this takes a tiny bit of time). I think that is what you were seeing.
