### ISSUE TITLE
Search not working CORS Error

### ISSUE THREAD

**Issue by raldred** [bower/search#73]
Search is failing, looks like a CORS error or broken search app.

Firefox:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bower-component-list.herokuapp.com/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Chrome: 

    Failed to load resource: the server https://bower-component-list.herokuapp.com/ responded with a status of 418 (I'm a teapot)
    XMLHttpRequest cannot load https://bower-component-list.herokuapp.com/.
    No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://bower.io' is therefore not allowed access. The response had HTTP status code 418.

**Comment by ArunMichaelDsouza** [comment]
+1, facing same issue on Chrome.

**Comment by hak8or** [comment]
Same thing on my end for firefox 40.0.2 on Arch linux.

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bower-component-list.herokuapp.com/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).```

**Comment by t0f3rchr15** [comment]
+1 facing same issue on Chrome

**Comment by miguelrincon** [comment]
+1 Seems the issue is still present.

**Comment by paulohp** [comment]
I'm not able to reproduce on OS X Chrome and OS X Safari.

Can you guys provide [more info](https://github.com/bower/bower/wiki/Report-a-Bug) ?

**Comment by BenMann** [comment]
@paulohp same here, can't replicate (chrome/FF on OS X). Maybe fixed but not closed?

**Comment by hak8or** [comment]
It seems to be working here now as well on chrome.

**Comment by BenMann** [comment]
Awesome. Going to close for now — Let us know if the problem re-surfaces.

**Comment by JeffJacobson** [comment]
I am currently getting this same error. I have tried both Chrome and Firefox Developer Edition.
