### ISSUE TITLE
Search is not updating

### ISSUE THREAD

**Issue by Fetz** [bower/search#74]
When I was renaming the project to be consistent with another project, by mistake I register the wrong url in bower, so I unregister the package and register again.

But even so in the search still appearing the wrong url:

 `http://bower.io/search/?q=VPAIDFLASHClient`

But in cli:
```
❯ bower info VPAIDFLASHClient
bower VPAIDFLASHClient#*        cached git://github.com/MailOnline/VPAIDFLASHClient.git#0.0.8
bower VPAIDFLASHClient#*      validate 0.0.8 against git://github.com/MailOnline/VPAIDFLASHClient.git#*
```

**Comment by paulohp** [comment]
Hey @Fetz, the issue is still happening for you? if yes, can you provide more [info](https://github.com/bower/bower/wiki/Report-a-Bug) about? I'll try to reproduce here too.

**Comment by Fetz** [comment]
I tested and now is ok, maybe was some cache issue in bower search.
