### ISSUE TITLE
I can't to find my plugin

### ISSUE THREAD

**Issue by tamtakoe** [bower/search#77]
I can't to find my plugin https://github.com/tamtakoe/oi.select through search form

Maybe because it contains dot in name?

**Comment by davidjbradshaw** [comment]
Give it 24 hours to show up.

On Mon, Aug 31, 2015 at 1:52 PM, tamtakoe <notifications@github.com> wrote:

> https://github.com/tamtakoe/oi.select
>
> Maybe because it contains dot in name?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bower/search/issues/77>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek

**Comment by tamtakoe** [comment]
it's come, thank!
