### ISSUE TITLE
Repository name 'angular-latest' gets replaced with 'tfeslee-temp'

### ISSUE THREAD

**Issue by michaelkrone** [bower/search#85]
When opening http://bower.io/search/, it lists the most popular repositories.
The name of 'angular-latest' is immediately replaced with 'tfeslee-temp'. This looks like a bug to me, can anyone explain this behaviour?

**Comment by accommodavid** [comment]
It's a known bug. See bower/bower.github.io#205

**Comment by michaelkrone** [comment]
Thank you
