### ISSUE TITLE
nifty-nav not appearing

### ISSUE THREAD

**Issue by desandro** [bower/search#86]
Reposting bower/registry#177 from @erwstout  here

---

We have a package called `nifty-nav` that doesn't appear in the search registry. Any thoughts?

Our `bower.json`:

```json
{
  "name": "nifty-nav",
  "description": "Nifty Nav is a quick and easy navigation plugin using Sass and jQuery. It makes making navigation systems a little better.",
  "main": "nifty-nav.js",
  "authors": [
    "Eric Stout / Factor1 <eric@factor1studios.com>"
  ],
  "license": "MIT",
  "keywords": [
    "Navigation",
    "Mobile",
    "Navigation",
    "Nav",
    "Mobile",
    "Nav",
    "Nifty",
    "Nav",
    "factor1"
  ],
  "homepage": "https://github.com/factor1/nifty-nav",
  "moduleType": [],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```

It does appear when searching via command line:

```
bower search nifty-nav
Search results:

nifty-nav git://github.com/factor1/nifty-nav.git
```

Thanks!

**Comment by erwstout** [comment]
Thanks @desandro

**Comment by erwstout** [comment]
Any updates or thought on this? Thanks.

**Comment by erwstout** [comment]
This was resolved and can be closed.

**Comment by BenMann** [comment]
@erwstout just out of curiosity.. what caused/solved it?

**Comment by erwstout** [comment]
@BenMann A development mistake on our end I believe. The `package.json` file was inside a folder and not in the git root. So I restructured the repo a bit and then unregistered the package and re-registered it and it fixed it.
